### ISSUE TITLE
Reemplazar boton del listado por el componente compartido Button 

### ISSUE THREAD

**Issue by fmarilao** [AlexLealInchcape/crud-front-app#10]
cada boton debera ejecutar la misma accion que tiene actualmente

![image](https://user-images.githubusercontent.com/72152713/194150019-63ca90bf-6a94-49b6-887b-2b3168268642.png)

**Comment by imekinox** [comment]
`components/molecules/UserList/UserList.js`

![CleanShot 2022-10-06 at 08 26 40@2x](https://user-images.githubusercontent.com/165823/194325252-682a7ca2-f0ea-4210-a1d2-5056b26824f7.png)
 Usar` src/components/atom/Button.jsx`

**Comment by Bortosh** [comment]
complete
