### ISSUE TITLE
limpiar seach al hacer click en mostrar todos

### ISSUE THREAD

**Issue by fmarilao** [AlexLealInchcape/crud-front-app#41]
al hacer click en mostrar todos deberia limpiar el input search y actualizar la lista con todos los users

ademas borrar el boton BUSCAR ya que no se utiliza

![image](https://user-images.githubusercontent.com/72152713/194637755-ac74f84e-1c91-428c-b969-fb3fd81729b8.png)

**Comment by Bortosh** [comment]
complete
